# Тема 10. Декораторы и исключения
Отчет по теме №10 выполнен :
- Баталова Полина Андреевна
- ПИЭ-21-1
  
| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + | 
| Задание 5 | + | + | 

знак «+» — задание выполнено; знак «-» — задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для
100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи.
P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания.

``` python
from functools import lru_cache

@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

if __name__ == '__main__':
    print(fibonacci(100))
```

### Результат
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/51064a1b-7f00-47d1-9e7f-622aa7584c57)

## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130.
Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.

``` python 
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)
        
    return output_func

@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")

if __name__ == '__main__':
    personal_info('Владимир', 38)
    personal_info('Александр', -5)
    personal_info('Петр', 138, 15, 48, 2)
```

### Результат
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/975c1997-a18f-4d5c-b0e8-385696e1e8f9)

## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.

``` python 
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')

if __name__ == '__main__':
    data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```

### Результат
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/afe1dd92-be01-4b5d-893b-e305d02503ba)

## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”

``` python 
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name) > 10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')

if __name__ == '__main__':
    name = '12345678910'
    check_name(name)
```

### Результат
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/8a2dcf33-bb33-4492-9191-0a806a789788)
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/2db040f0-ee44-4c72-b141-23971db88429)

## Лабораторная работа №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: 		init		() (вызывается при создании класса декоратора в программе) и 	call	() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

``` python 
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> Проверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного включения')

@SiteChecker
def site():
    print('Усердная работа сайта')

if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```

### Результат
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/41394f8d-d2cd-45f5-bb75-93d401522318)

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции:
```
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
Результатом вашей работы будет листинг кода и скриншот консоли, в
котором будет выполненная функция Фибоначчи и время выполнения программы.

``` python
import time

def calculate_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Время выполнения функции {func.__name__}: {end_time - start_time} секунд")
        return result
    return wrapper

@calculate_time
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```

### Результат 
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/4138c29d-b4a8-4430-8a5a-b099c277805e)

### Выводы
- Библиотека `time` импортируется в начале программы.
- Функция `calculate_time` принимает функцию в качестве аргумента и возвращает обертку, которая измеряет время выполнения функции и выводит результат на экран.
- Декоратор `@calculate_time` применяется к функции `fibonacci`, чтобы измерить время выполнения этой функции.
- Функция `fibonacci` вычисляет числа Фибоначчи до 200 и выводит их на экран.

## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.


``` python
try:
    with open('empty_file.txt', 'r') as file:
        data = file.read()
        if not data:
            raise Exception("файл пустой")
        else:
            print(data)
except Exception as e:
    print(e)

try:
    with open('non_empty_file.txt', 'r') as file:
        data = file.read()
        if not data:
            raise Exception("файл пустой")
        else:
            print(data)
except Exception as e:
    print(e)
```

### Результат 
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/d2276cc5-688a-488d-a4bf-2a324e48a2e6)

### Выводы
- Этот код демонстрирует использование блока `try-except` для обработки исключений при работе с файлами. 

- В первом блоке `try` программа пытается открыть файл `empty_file.txt` и прочитать его содержимое. Если файл пустой, то возникает исключение, которое обрабатывается в блоке `except`, и выводится сообщение "файл пустой".

- Во втором блоке `try` программа открывает файл `non_empty_file.txt` и успешно читает его содержимое, которое затем выводится на экран.

- Таким образом, этот код демонстрирует, как обрабатывать исключения при работе с файлами, и как можно проверять наличие данных в файле перед его обработкой.

## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

``` python
def add_two_numbers():
    try:
        num = int(input("Введите число: "))
        result = 2 + num
        print("Результат сложения:", result)
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

# Тест 1: ввод числа
add_two_numbers()

# Тест 2: ввод строки
add_two_numbers()

# Тест 3: ввод другого неподходящего типа данных
add_two_numbers()
```

### Результат 
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/017c97a3-bb8d-4c73-9269-7969f2ec9f7d)

### Выводы
- Этот код представляет функцию `add_two_numbers()`, которая запрашивает у пользователя ввод числа, затем пытается сложить это число с 2 и выводит результат.
- Если пользователь вводит нечисловое значение, то функция перехватывает исключение `ValueError` и выводит сообщение о неподходящем типе данных.

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

``` python
# Создаем класс декоратора
class my_decorator:
    def __init__(self, func):  # Инициализируем класс, принимая функцию в качестве аргумента
        self.func = func

    def __call__(self, *args, **kwargs):  # Метод вызывается при вызове декорированной функции
        print("Декоратор добавляет новое поведение к функции")  # Выводим сообщение перед выполнением функции
        return self.func(*args, **kwargs)  # Вызываем исходную функцию с переданными аргументами

# Определяем две функции, к которым будем применять декоратор
@my_decorator  # Применяем декоратор к функции greet
def greet(name):  # Определяем функцию greet
    print(f"Привет, {name}!")  # Выводим приветствие с переданным именем

@my_decorator  # Применяем декоратор к функции square
def square(n):  # Определяем функцию square
    return n * n  # Возвращаем квадрат переданного числа

# Вызываем функции
greet("Полина")  # Вызываем функцию greet с именем 
result = square(5)  # Вызываем функцию square с числом 
print("Результат возведения в квадрат:", result)  # Выводим результат возведения в квадрат
```

### Результат 
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/083244bd-7272-459d-b0c3-30c7cc78a32d)

### Выводы
- Создали класс `my_decorator`, который принимает функцию в качестве аргумента и возвращает новую функцию.
- Метод `__call__` класса `my_decorator` вызывается при вызове декорированной функции. В данном случае он выводит сообщение перед выполнением функции.
- Применили декоратор к двум функциям `greet` и `square`, добавляя им новое поведение.
- При вызове функций `greet` и `square`, декоратор выводит сообщение и затем вызывает исходные функции.

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

``` python
# Создаем собственное исключение
class ValueTooSmallError(Exception):
    def __init__(self, message="Значение слишком мало"):
        self.message = message
        super().__init__(self.message)

# Используем исключение в первом фрагменте кода
def divide_numbers(x, y):
    if y <= 0:
        raise ValueTooSmallError("Знаменатель должен быть больше нуля")
    return x / y

try:
    result = divide_numbers(10, 0)  # Вызываем функцию divide_numbers с аргументами 10 и 0
except ValueTooSmallError as e:  # Ловим исключение ValueTooSmallError
    print(e)  # Выводим сообщение об ошибке

# Используем исключение во втором фрагменте кода
def calculate_area(length, width):
    if length <= 0 or width <= 0:
        raise ValueTooSmallError("Значения длины и ширины должны быть больше нуля")
    return length * width

try:
    area = calculate_area(-5, 10)  # Вызываем функцию calculate_area с аргументами -5 и 10
except ValueTooSmallError as e:  # Ловим исключение ValueTooSmallError
    print(e)  # Выводим сообщение об ошибке
```

### Результат 
![image](https://github.com/polyyBa/Software_Engineering/assets/144797777/62e41ca0-5414-415c-a1d8-2e19e282ec51)

### Выводы
- Создается собственное исключение `ValueTooSmallError` с сообщением по умолчанию "Значение слишком мало".
- Функция `divide_numbers` проверяет, что знаменатель больше нуля, иначе вызывает исключение `ValueTooSmallError`.
- В блоке `try-except` вызывается функция `divide_numbers` с аргументами 10 и 0, и ловится исключение `ValueTooSmallError`, выводится сообщение об ошибке.
- Функция `calculate_area` проверяет, что значения длины и ширины больше нуля, иначе вызывает исключение `ValueTooSmallError`.
- Во втором блоке `try-except` вызывается функция `calculate_area` с аргументами -5 и 10, и ловится исключение `ValueTooSmallError`, выводится сообщение об ошибке.
